version: '3.7'

services:
  traefik:
    image: traefik:2.2
    command:
      - '--log.level=WARN'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=proxy_net'
      - '--entryPoints.http.address=:80'
      - '--entryPoints.http.http.redirections.entryPoint.to=https'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.https.http.tls=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.email=user@my.domain.com'
      - '--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: certificates
        target: /etc/traefik/acme
    networks:
      - proxy_net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == node-01 # node-01 is manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  whoami:
    image: containous/whoami
    networks:
      - proxy_net
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.http_whoami.rule: 'Host(`whoami.my.domain`)'
        traefik.http.routers.http_whoami.entrypoints: 'http'
        traefik.http.routers.https_whoami.rule: 'Host(`whoami.my.domain`)'
        traefik.http.routers.https_whoami.entrypoints: 'https'
        traefik.http.routers.https_whoami.tls.certresolver: 'letsencrypt'
        traefik.http.services.whoami.loadbalancer.server.port: '80'

networks:
  proxy_net:
    external: true

volumes:
  certificates:
